// export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
// export const ADD_PRODUCT = "ADD_PRODUCT";
// export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
// export const DELETE_PRODUCT = "DELETE_PRODUCT";
// export const EDIT_PRODUCT = "EDIT_PRODUCT";

export const LOGIN = "LOGIN";

export const RESET_FETCH_RESOURCE = "RESET_FETCH_RESOURCE";
export const FETCH_RESOURCES_SUCCESS = "FETCH_RESOURCES_SUCCESS";
export const FETCH_RESOURCES_FAIL = "FETCH_RESOURCES_FAIL";
export const NOTIFY = "NOTIFY";
export const GET_LISTADMIN = "GET_LISTADMIN";
export const GET_GAMEBYID = "GET_GAMEBYID";
export const GET_LISTGAME = "GET_LISTGAME";
export const GET_QUESTIONBYID = "GET_QUESTIONBYID";
export const GET_LISTQUESTIOB = "GET_LISTQUESTIOB";
export const GET_LISTINFOGAME = "GET_LISTINFOGAME";
export const GET_LISTUSER = "GET_LISTUSER";
export const GET_LISTGAMEUSER = "GET_LISTGAMEUSER";
export const GET_LISTACCADMIN = "GET_LISTACCADMIN";
export const GET_LISTINFO = "GET_LISTINFO";
export const GET_USERBYID = "GET_USERBYID";

export const GET_BANNERBYID = "GET_BANNERBYID";
export const GET_LISTBANNER = "GET_LISTBANNER";