// export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
// export const ADD_PRODUCT = "ADD_PRODUCT";
// export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
// export const DELETE_PRODUCT = "DELETE_PRODUCT";
// export const EDIT_PRODUCT = "EDIT_PRODUCT";

export const LOGIN = "LOGIN";

export const RESET_FETCH_RESOURCE = "RESET_FETCH_RESOURCE";
export const FETCH_RESOURCES_SUCCESS = "FETCH_RESOURCES_SUCCESS";
export const FETCH_RESOURCES_FAIL = "FETCH_RESOURCES_FAIL";
export const NOTIFY = "NOTIFY";
export const GET_LISTADMIN = "GET_LISTADMIN";
export const GET_GAMEBYID = "GET_GAMEBYID";
export const GET_LISTGAME = "GET_LISTGAME";
export const GET_QUESTIONBYID = "GET_QUESTIONBYID";
export const GET_LISTQUESTIOB = "GET_LISTQUESTIOB";
export const GET_LISTINFOGAME = "GET_LISTINFOGAME";
export const GET_LISTUSER = "GET_LISTUSER";
export const GET_LISTGAMEUSER = "GET_LISTGAMEUSER";
export const GET_LISTACCADMIN = "GET_LISTACCADMIN";
export const GET_LISTINFO = "GET_LISTINFO";
export const GET_USERBYID = "GET_USERBYID";

export const GET_BANNERBYID = "GET_BANNERBYID";
export const GET_LISTBANNER = "GET_LISTBANNER";
export const DELETE_BANNER = "DELETE_BANNER";

export const GET_ENTERPRISEBYID = "GET_ENTERPRISEBYID";
export const GET_LISTENTERPRISE = "GET_LISTENTERPRISE";
export const DELETE_ENTERPRISE = "DELETE_ENTERPRISE";

export const GET_EVENTBYID = "GET_EVENTBYID";
export const GET_LISTEVENT = "GET_LISTEVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const GET_FACTBYID = "GET_FACTBYID";
export const GET_LISTFACT = "GET_LISTFACT";
export const DELETE_FACT = "DELETE_FACT";

export const GET_NEWSBYID = "GET_NEWSBYID";
export const GET_LISTNEWS = "GET_LISTNEWS";
export const DELETE_NEWS = "DELETE_NEWS";

export const GET_VIDEOBYID = "GET_VIDEOBYID";
export const GET_LISTVIDEO = "GET_LISTVIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";

export const GET_ACCOUNTBYID = "GET_ACCOUNTBYID";
export const GET_LISTACCOUNT = "GET_LISTACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const GET_REGISTERBYID = "GET_REGISTERBYID";
export const GET_LISTREGISTER = "GET_LISTREGISTER";
export const DELETE_REGISTER = "DELETE_REGISTER";


